export const listedcarsData = [
  {
    id: 1,
    title: 'Mahindra XUV700',
    subTitle: '3.5 DS PowerPulse Momentum 5dr A',
    specs: ['21l mpg', '27868 cc', 'Petrol'],
    priceMain: 'AED 450',
    priceSub: '400',
    image: '/images/Listed-car-0.png',
  },
  {
    id: 2,
    title: 'Mahindra Thar',
    subTitle: '3.5 DS PowerPulse Momentum 5dr A',
    specs: ['21l mpg', '27868 cc', 'Petrol'],
    priceMain: 'AED 460',
    priceSub: '400',
    image: '/images/Listed-car-1.png',
  },
  {
    id: 3,
    title: 'Audi',
    subTitle: '3.5 DS PowerPulse Momentum 5dr A',
    specs: ['21l mpg', '27868 cc', 'Petrol'],
    priceMain: 'AED 480',
    priceSub: '400',
    image: '/images/Listed-car-2.png',
  },
  {
    id: 4,
    title: 'Mahindra XUV700',
    subTitle: '3.5 DS PowerPulse Momentum 5dr A',
    specs: ['21l mpg', '27868 cc', 'Petrol'],
    priceMain: 'AED 455',
    priceSub: '400',
    image: '/images/Listed-car-3.png',
  },
  {
    id: 5,
    title: 'Mahindra XUV700',
    subTitle: '3.5 DS PowerPulse Momentum 5dr A',
    specs: ['21l mpg', '27868 cc', 'Petrol'],
    priceMain: 'AED 450',
    priceSub: '400',
    image: '/images/Listed-car-4.png',
  },
  {
    id: 6,
    title: 'Mahindra Thar',
    subTitle: '3.5 DS PowerPulse Momentum 5dr A',
    specs: ['21l mpg', '27868 cc', 'Petrol'],
    priceMain: 'AED 445',
    priceSub: '400',
    image: '/images/Listed-car-5.png',
  },
  {
    id: 7,
    title: 'Audi',
    subTitle: '3.5 DS PowerPulse Momentum 5dr A',
    specs: ['21l mpg', '27868 cc', 'Petrol'],
    priceMain: 'AED 475',
    priceSub: '400',
    image: '/images/Listed-car-6.png',
  },
  {
    id: 8,
    title: 'Mahindra XUV700',
    subTitle: '3.5 DS PowerPulse Momentum 5dr A',
    specs: ['21l mpg', '27868 cc', 'Petrol'],
    priceMain: 'AED 460',
    priceSub: '400',
    image: '/images/Listed-car-7.png',
  },
  {
    id: 8,
    title: 'Mahindra XUV700',
    subTitle: '3.5 DS PowerPulse Momentum 5dr A',
    specs: ['21l mpg', '27868 cc', 'Petrol'],
    priceMain: 'AED 460',
    priceSub: '400',
    image: '/images/Listed-car-8.png',
  },
  {
    id: 8,
    title: 'Mahindra XUV700',
    subTitle: '3.5 DS PowerPulse Momentum 5dr A',
    specs: ['21l mpg', '27868 cc', 'Petrol'],
    priceMain: 'AED 460',
    priceSub: '400',
    image: '/images/Listed-car-9.png',
  },
];